### ISSUE TITLE
enhance the UI/UX of the reset password page

### ISSUE THREAD

**Issue by Alvish0407** [rawsun007/Recipe-Box#2]
`The password is too similar to the first name.` Should be in red color. It's unnoticeable in current state.

<img width="641" alt="Screenshot 2024-11-20 at 10 39 32 AM" src="https://github.com/user-attachments/assets/67be99e3-891d-4959-853d-c5bc9c9217d4">

**Comment by rawsun007** [comment]
Thank you for raising this concern about the password error message visibility. The issue has been addressed, and the error messages now appear in red for better visibility and user experience. If you notice any other improvements, feel free to share! Closing this issue now.
