### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by Alvish0407** [rawsun007/Recipe-Box#4]
<img width="684" alt="Screenshot 2024-11-20 at 10 43 13 AM" src="https://github.com/user-attachments/assets/fddb34cc-a879-4fb8-b0fc-447622254f41">

**Comment by rawsun007** [comment]
Thank you for bringing this to my attention. The favicon issue has been successfully resolved, and it should now display correctly across all pages. If you encounter any further issues, feel free to reach out. Closing this issue now.  
![{274AE26A-A324-4C36-8E70-54B4A67A300C}](https://github.com/user-attachments/assets/5c73d3d2-303c-433d-9fe5-b48f36716db0)
